name: "Taggear la imagen docker"
description: "Se etiqueta la imagen de docker antes de subirla al registry"
inputs:
  image_name:
    description: "Nombre de la imagen"
    required: true

  version:
    description: "version de la app"
    required: true

outputs:
  full_name:
    description: "Nombre completo de la imagen docker"

runs:
  using: "composite"
  steps:
    - name: mostrar directorio
      shell: bash
      run: ls -la

    - name: extraer inputs
      id: name_complete
      shell: bash
      run: |
        image_name=${{inputs.image_name}}
        version=${{inputs.version}}

        nombre_completo="$image_name:$version"
        echo "el nombre completo de la imagen es: $nombre_completo"

        echo "full_name=$nombre_completo" >> $GITHUB_OUTPUT

    - name: Verificar si el output se generó correctamente
      shell: bash
      run: |
        echo "${{steps.name_complete.outputs.full_name}}"
        

