on:
  workflow_dispatch:
    
jobs:
  ci: 
    runs-on: ubuntu-latest
    
    steps:
      - name: clonamos repo
        uses: actions/checkout@v4

      - name: Se obtiene la version
        id: tomar_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "La version del la app es: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: accion composite
        uses: ./.github/actions/taggear-imagen
        id: tag
        env:
          username: ${{ vars.DOCKER_USERNAME}}
        with:
          image_name: "mi-app-angular"
          version: "${{steps.tomar_version.outputs.version}}"

      - name: Mostrar imagen completa
        run: echo ${{ steps.tag.outputs.tag}} 
