on:
  workflow_dispatch:
    
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: accion composite
        uses: ./.github/actions/taggear-imagen
        id: tag
        env:
          username: ${{ vars.DOCKER_USERNAME }}
        with:
          image_name: "mi-app-angular"
          version: "${{steps.tomar_version.outputs.version}}"

      - name: hacer run del contenedor
        run: ${{ steps.tag.outputs.tag}} 

      - name: comprobar el despliegue haciendo curl
        run: curl http://localhost:8080