on:
  workflow_dispatch:
    
jobs:
  ci: 
    runs-on: ubuntu-latest
    
    steps:
      - name: clonamos repo
        uses: actions/checkout@v4
        
      - name: accion composite
        uses: ./.github/actions/taggear-imagen