on:
  workflow_call:
    inputs:
      imagen_docker_completa:
        required: true
        type: string
    
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: hacemos pull de la imagen
        run: docker pull ${{inputs.imagen_docker_completa}}

      - name: hacer run del contenedor
        run: docker run -dit -p 8080:8080 ${{inputs.imagen_docker_completa}} 

      - name: comprobar el despliegue haciendo curl
        run: curl http://localhost:8080
