on:
  workflow_dispatch:
  
  push:
    branches:
      - main
      - development

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio de ci/cd 
        run: echo "Se inicia la integracion y despliegue continuo"

  llamar_ci:
    needs: ci-cd
    uses: ./.github/workflows/continuousIntegration.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  
  job_comprobar_imagen:
    needs: llamar_ci
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.llamar_ci.outputs.tag_image}}

  # cd_prod:
  #   if: github.ref == 'refs/heads/main'
  #   environment:
  #     name: produccion
  #   needs: llamar_ci
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: continuous deployment
  #       run: echo "Se efectua el CD!"

  # efectuar_cd_prod:
  #   needs: cd_prod
  #   uses: ./.github/workflows/continuousDeployment.yaml
  #   with: 
  #     imagen_docker: ${{needs.llamar_ci.outputs.tag_image}}

  
  # cd_uat:
  #   if: github.ref == 'refs/heads/development'
  #   environment:
  #     name: uat
  #   needs: llamar_ci
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: continuous deployment
  #       run: echo "Se efectua el CD!"
  
  # efectuar_cd_uat:
  #   needs: cd_uat
  #   uses: ./.github/workflows/continuousDeployment.yaml
  #   with:
  #     imagen_docker: ${{needs.llamar_ci.outputs.tag}}
  

