on:
  workflow_dispatch:
  

jobs:
  llamar_ci:
    uses: ./.github/workflows/continuousIntegration.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  llamar_cd:
    needs: llamar_ci
    uses: ./.github/workflows/continuousDeployment.yaml
    