on:
  workflow_dispatch:
  
  push:
    branches:
      - main
      - development

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Inicio de ci/cd 
        run: echo "Se inicia la integracion y despliegue continuo"

  llamar_ci:
    needs: ci-cd
    uses: ./.github/workflows/continuousIntegration.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}

  tests:
    environment:
      name: produccion
    needs: llamar_ci
    runs-on: ubuntu-latest
    steps:
      - name: Pruebas 
        run: |
          echo "REALIZANDO TESTS DE COBERTURA..."
          echo "TESTS SUPERADOS CON EXITO!!"

  efectuar_cd_prod:
    needs: tests
    uses: ./.github/workflows/continuousDeployment.yaml
  
  cd_uat:
    environment:
      name: uat
    needs: llamar_ci
    runs-on: ubuntu-latest
    steps:
      - name: continuous deployment
        run: echo "Se efectua el CD!"
  
  efectuar_cd_uat:
    needs: cd_uat
    uses: ./.github/workflows/continuousDeployment.yaml
  

